server:
  servlet:
    context-path: /api
  port: 8080

spring:
  profiles:
    include:
      - db
  datasource:
    driver-class-name: ${db-driver}
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
