server:
  servlet:
    context-path: /api
  port: 8080

spring:
  profiles:
    include:
      - db
      - jwt
  datasource:
    driver-class-name: ${db-driver}
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-clientId}
            client-secret: ${google-clientSecret}
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8080/api/oauth2/callback/google

logging.level:
  org.hibernate:
    sql: debug
    type : trace